# Generated by Django 4.0.3 on 2022-03-15 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('code_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
