# Generated by Django 4.0.3 on 2022-03-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_dislike_project_likes_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dislike',
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.CharField(choices=[('like', 'Like')], max_length=200),
        ),
    ]
