# Generated by Django 4.0.3 on 2022-03-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_dislike_alter_like_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=200),
        ),
    ]
