# Generated by Django 4.0.3 on 2022-03-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_dislike_alter_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='project',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
